### ISSUE TITLE
Unverified Digital Signiture (Linux Community Net) Failed to Install on Windows 7

### ISSUE THREAD

**Issue by alan33d** [beagleboard/beaglebone-getting-started#13]
Downloaded BONE_D64.exe and Windows prompted that it can't installed one of the components due to an invalid digital signature.  I downloaded the latest version from GitHub.

**Comment by RobertCNelson** [comment]
@alan33d microsoft broke our signed drivers:

https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

Regards,

**Comment by Ginawa** [comment]
This driver issue is really a headache, us like a company we are currently having customers failing the installation in all Windows versions. 

"Disable Windows Driver Signature Check" or installing a "compatible Microsoft Driver" is not a solution for a product!

The last update of the driver licence was on Jan 19, 2016 7:57:38 PM. Any update on this??

**Comment by jadonk** [comment]
I did update the certificate and resigned (2c82662d37750d5d62a46232dba3bf7cb6c15584), but I still don't have an EV certificate, so I don't know if it'll work for the new Windows 10 update.

**Comment by Ginawa** [comment]
I just tested the new signed drivers on windows 10 Pro version 1607 and are working great.

Thank you very much for your support!
