### ISSUE TITLE
Start.html Missing images

### ISSUE THREAD

**Issue by RobertCNelson** [beagleboard/beaglebone-getting-started#17]
@jadonk 

Books
For a complete list of books on BeagleBone, see beagleboard.org/books.

https://i.imgur.com/nWmjf9h.png

Regards,

**Comment by jadonk** [comment]
@RobertCNelson I've integrated the images into the site. https://github.com/beagleboard/beaglebone-getting-started/commit/e944d74e080209f7ad58551c7a867b93dde2a75c

**Comment by RobertCNelson** [comment]
looks good! and pushed out to the repo. ;)
